### ISSUE TITLE
Schema comparator not working

### ISSUE THREAD

**Issue by elmalto** [3logic/apollo-cassandra#8]
I have the following fields:

    {
      "fields": {
      "name": {
        "type": "text"
      },
      "email": {
        "type": "text"
      },
      "role": {
        "type": "text"
      },
      "hashedpassword": {
        "type": "text"
      },
      "provider": {
        "type": "text"
      },
      "salt": {
        "type": "text"
      },
      "password": {
        "type": "text"
      },
      "profile": {
        "type": "text"
      }
    },
      "key": [
      [
        "name"
      ]
    ]
    }

My Cassandra DB returns:

    {
      "fields": {
      "email": {
        "type": "text"
      },
      "hashedpassword": {
        "type": "text"
      },
      "name": {
        "type": "text"
      },
      "password": {
        "type": "text"
      },
      "profile": {
        "type": "text"
      },
      "provider": {
        "type": "text"
      },
      "role": {
        "type": "text"
      },
      "salt": {
        "type": "text"
      }
    },
      "key": [
      [
        "name"
      ]
    ]
    }

and I get the error:

apollo.model.tablecreation.schemamismatch: Given Schema does not match existing DB Table

Might be a bug in lodash?

**Comment by ecogodi** [comment]
Should be fixed in master (1.0.5)

**Comment by edgracilla** [comment]
If someone needs to support cassandra v2 and suddenly faced this blocking wall here's what I found.

The error message `Given Schema does not match existing DB Table 'table_name'` is valid. The reason is model properties were parsed and reassigned alphabetically. I dug into `base_model.js` and logged those comparison values in console and here is the result.
### normalized_model_schema
> { fields:
   { id: { type: 'uuid' },
     data_id: { type: 'bigint' },
     co2: { type: 'text' },
     temp: { type: 'int' },
     quality: { type: 'float' },
     reading_time: { type: 'timestamp' },
     metadata: { type: 'map', typeDef: '<text,text>' },
     list: { type: 'list', typeDef: '<text>' },
     set: { type: 'set', typeDef: '<text>' },
     random_data: { type: 'text' },
     is_normal: { type: 'boolean' },
     created: { type: 'timestamp' } } }

### normalized_db_schema
> { fields:
   { co2: { type: 'text' },
     created: { type: 'timestamp' },
     data_id: { type: 'bigint' },
     id: { type: 'uuid' },
     is_normal: { type: 'boolean' },
     list: { type: 'list', typeDef: '<text>' },
     metadata: { type: 'map', typeDef: '<text,text>' },
     quality: { type: 'float' },
     random_data: { type: 'text' },
     reading_time: { type: 'timestamp' },
     set: { type: 'set', typeDef: '<text>' },
     temp: { type: 'int' } } }

I updated my model and aligned them same as in `normalized_db_schema` then it was resolved

I am using `express-cassandra@0.5.4` which relies to `apollo-cassandra`
